---
name: Release Docker

on:
    workflow_dispatch:

    push:
        branches:
            - "main"
        tags:
          - 'v*'

jobs:
    docker-release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - uses: actions/setup-go@v2
              with:
                go-version: 1.21.3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }} 
            - name: get latest tag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              id: get-latest-tag
              with:
                fallback: latest           
            - name: Build the docker image
              run: |
                    docker build . -f Dockerfile --tag beclab/headscale-api-wrapper:${{ steps.get-latest-tag.outputs.tag }}
                    docker push beclab/headscale-api-wrapper:${{ steps.get-latest-tag.outputs.tag }}




